# Generated by Django 4.2.30 on 2026-09-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('interval_days', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (14, 'Every 2 weeks'), (30, 'Monthly')], default=7)),
                ('next_due', models.DateField()),
                ('rotation', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=4)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=80)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chores', to='chores.roommate')),
                ('source_recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.recurringchore')),
            ],
        ),
    ]
